template = ""
rev_id = 4
template_sha = "87be02986858c4b7ae5e8613b6f951c3c209b221"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "myv"
__UND2C_TRG__ = "de"
__UNDEFINED_SOURCE__ = "Erzya"
__UNDEFINED_TARGET__ = "German"
__UND_SRC__ = "myv"
__UND_TRG__ = "deu"
